In [26]:
import numpy as np

In [27]:
def done(a):
    C=a-a.mean(axis=1, keepdims=True)
    print(C)

In [29]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [31]:
done(a)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
